title: surf-connect
description: A website to connect with other surfers and view surf forecasts around Oahu.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions